Models hub m11.1
JohnSnowLabs/spark-nlp pull request #6457
Opened 2021-11-12 12:29 UTC by gadde5300

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-11-14 14:28 UTC, HashamUlHaq commented
Hi @gadde5300 you have changed all ner models to ner_jsl_enriched. which is not correct. 

- For the chemprot model, keep the ner model to "ner_chemprot_clinical" and do not define relation pairs.
- For redl_clinical, the ner model should be "ner_clinical" and set these relations: ["problem-test", "problem-treatment"]
- in redl_date correct "delative" to "relative" on line 78
- ner model in redl_drug_drug interaction is also not correct.
- ner model for redl_temporal_events is also not correct.

Please refer to these notebooks and change all ner models and relation pairs properly:
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Healthcare/10.Clinical_Relation_Extraction.ipynb
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Healthcare/10.1.Clinical_Relation_Extraction_BodyParts_Models.ipynb

2021-11-15 09:26 UTC, josejuanmartinez approved these changes
Everything looks good to me, @gadde5300 . Thank you so much!

2021-11-15 15:49 UTC, josejuanmartinez requested changes
Hi @gadde5300 !

I added one request, since I see a strange colab notebook (ner) for a classifier dl pipeline.

2021-11-15 15:49 UTC, josejuanmartinez commented on docs/_posts/murat-gunay/2021-11-04-classifierdl_use_sentiment_pipeline_tr.md
> +[Open in Colab](https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Healthcare/1.Clinical_Named_Entity_Recognition_Model.ipynb){:.bu
I don't think this is correct. classifier_dl_use_sentiment_pipeline is not an NER model.

2021-11-15 16:36 UTC, josejuanmartinez approved these changes
Looks good now. Thank you!

2021-11-15 16:42 UTC, merged