Added predicted entities to bert_token_classifier_ner_btc
JohnSnowLabs/spark-nlp pull request #6561
Opened 2021-12-04 10:50 UTC by gadde5300

## Description

Added "Predicted Entities" to bert_token_classifier_ner_btc.

## Motivation and Context

It fixes the issue [#763](https://github.com/JohnSnowLabs/streamlit-demo-apps/issues/763)

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-12-04 11:21 UTC, murat-gunay requested changes
the Predicted Entities section accepts only exact entity names separated by commas (,) without Person, Location or Organization or period (.) . Should be :

`PER`, `LOC`, `ORG`

2021-12-04 18:23 UTC, murat-gunay approved these changes

2021-12-06 08:59 UTC, josejuanmartinez approved these changes
It looks good to me. Sent it to Veysel for merging.

2021-12-06 09:15 UTC, vkocaman commented
`uses the Deep Learning (torch) algorithm` >> do we really need to say this ?

2021-12-06 10:21 UTC, josejuanmartinez commented
@vkocaman  thanks for spotting this out. I checked the changes only, not the original page. And there are several more things there:
1) `Description`: This model is trained on Broad Twitter Corpus (BTC) dataset, so that it can detect entities in Twitter-based texts successfully. It's based on bert_base_cased embeddings, which are included the model so, you don't need to use any embeddings components in the NLP pipeline.
2) Since we have this models in demo, can we use a better example with more entities? Dia didn't like the FUUULLHAM entity.
3) `data-set` : it's dataset.

2021-12-06 10:22 UTC, josejuanmartinez requested changes
@vkocaman thanks for spotting this out. I checked the changes only, not the original page. And there are several more things there:

Description: This model is trained on Broad Twitter Corpus (BTC) dataset, so that it can detect entities in Twitter-based texts successfully. It's based on bert_base_cased embeddings, which are included the model so, you don't need to use any embeddings components in the NLP pipeline.

Since we have this models in demo, can we use a better example with more entities? Sales people didn't like the FUUULLHAM entity.

data-set : it's dataset.

2021-12-06 11:09 UTC, josejuanmartinez requested changes
Can you apply these changes? Thank youi!

2021-12-06 11:09 UTC, josejuanmartinez commented on docs/_posts/murat-gunay/2021-09-09-bert_token_classifier_ner_btc_en.md
> +- It's based on `bert_base_cased embeddings, which are included the model so, you don't need to use any embeddings components in the NLP pipeline.
Missing quote after `bert_bassed_cased`

2021-12-06 11:09 UTC, josejuanmartinez commented on docs/_posts/murat-gunay/2021-09-09-bert_token_classifier_ner_btc_en.md
> +test_sentences = ["""Wengers big mistakes is not being ruthless enough with bad players.""", """my dream Fulham F.C. !!!.."""]
Can you remove second example and use this one?

![image](https://user-images.githubusercontent.com/36634572/144835637-5e84b6af-026f-4351-b6ca-f749b087ee9f.png)

2021-12-06 11:09 UTC, josejuanmartinez commented on docs/_posts/murat-gunay/2021-09-09-bert_token_classifier_ner_btc_en.md
> +val data = Seq("Wengers big mistakes is not being ruthless enough with bad players.", "my dream Fulham F.C. !!!..").toDF("text")
Can you remove second example and use this one?

![image](https://user-images.githubusercontent.com/36634572/144835637-5e84b6af-026f-4351-b6ca-f749b087ee9f.png)

2021-12-06 11:58 UTC, josejuanmartinez approved these changes
Looks good. Thank you.

2021-12-06 12:00 UTC, josejuanmartinez requested changes
This last thing and it's good to go.

2021-12-06 12:00 UTC, josejuanmartinez commented on docs/_posts/murat-gunay/2021-09-09-bert_token_classifier_ner_btc_en.md
> +- It's based on `bert_base_cased` embeddings, which are included the model so, you don't need to use any embeddings components in the NLP pipeline.
which are included `in the model, so you don't need to use any embeddinsg component in the NLP pipeline`

2021-12-06 12:08 UTC, josejuanmartinez approved these changes
Looks good! Sending it to merge!

2021-12-06 12:22 UTC, merged