sbiobertresolve md file updated
JohnSnowLabs/spark-nlp pull request #6668
Opened 2021-12-27 12:07 UTC by Cabir40

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-12-27 13:36 UTC, muhammetsnts requested changes
1. change the model name in the scala code as you did in python https://github.com/JohnSnowLabs/spark-nlp/blob/66c5c176513e7ae828f10d7531be590fe24491f5/docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_auxConcepts_en.md
2.

2021-12-27 14:37 UTC, muhammetsnts commented
Also please remove `\` from all  SCALA codes and use `"` instead of `'`
![image](https://user-images.githubusercontent.com/76607915/147481691-b3c7865d-961e-4781-9a23-e2673a1e6de9.png)

2021-12-27 16:20 UTC, josejuanmartinez requested changes
Several fixes needed for Scala code:
1) No `\` is needed at the end of each line when multiline code
2) There is no `[]` in Scala. We should use the `Array(, ... ,)` class. There are several errors with that.
3) Don't use single quotes in Scala. Everything should be in double quotes. You will see it highlighted in red by github.
4) setInputCols, since it's Cols, needs an Array, therefore you need Array().
5) Two double quotes `""` at the beginning or the end don't make sense in Scala, it should be either one double quote or, if you want multiline comments, then as in Python, three double quotes `"""` at the beginning and at the end.

This is all that I'v seen. Cheers!

2021-12-28 14:40 UTC, vkocaman commented
@josejuanmartinez  should I merge this ?

2021-12-28 15:03 UTC, josejuanmartinez requested changes
@muhammetsnts @vkocaman I reviewed the 77 files, sorry, it took some time. There are several issues, I commented each of them.

2021-12-28 15:03 UTC, josejuanmartinez commented on docs/_posts/muhammetsnts/2021-08-26-sbertresolve_icd10cm_slim_billable_hcc_med_en.md
> +val data = Seq("bladder cancer"9.toDS.toDF("text")
Typo: 9 after "bladder cancer"

2021-12-28 15:13 UTC, vkocaman commented
@josejuanmartinez  so, it is better to wait till it is all fixed then

2021-12-28 16:59 UTC, josejuanmartinez requested changes
Still some issues require attention :)

2021-12-28 16:59 UTC, josejuanmartinez commented on docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_umls_major_concepts_en.md
> +results = model.transform(data
You added another bracket. The problem was in:

`results = model.transform(data` <-- Here is the missing parenthesis.

Please remove the new bracket you added and add the parenthesis.

2021-12-28 16:59 UTC, josejuanmartinez commented on docs/_posts/muhammetsnts/2021-07-08-sbiobertresolve_snomed_bodyStructure_en.md
> +      .pretrained("sbiobertresolve_snomed_bodyStructure, "en", "clinical/models") \
Missing quotes after bodyStructure

2021-12-28 16:59 UTC, josejuanmartinez commented on docs/_posts/muhammetsnts/2021-07-08-sbiobertresolve_snomed_bodyStructure_en.md
> +      .pretrained("sbiobertresolve_snomed_bodyStructure, "en", "clinical/models")
Missing quotes after bodyStructure

2021-12-28 17:13 UTC, josejuanmartinez requested changes
I'm not 100% sure, but I think we are still missing an Array(), take a look

2021-12-28 17:13 UTC, josejuanmartinez commented on docs/_posts/muhammetsnts/2021-07-08-sbertresolve_snomed_bodyStructure_med_en.md
> +     .setInputCols("ner_chunk")
.setInputcols(Array("ner_chunk"))

2021-12-28 18:38 UTC, josejuanmartinez approved these changes
Possibly I missed a lot of things, because 77 files to take a look at are too much, but generally speaking it looks much better now than before. You can go on :) @vkocaman @Cabir40  @muhammetsnts

2021-12-30 07:53 UTC, muhammetsnts approved these changes
Good job! Thanks, @Cabir40  for this work and @josejuanmartinez for the great comments!

2021-12-30 09:32 UTC, muhammetsnts commented
According to new updates, this PR will be closed and all changes will be pushed in a new PR. (all `.setCaseSensitive(False)` lines will be deleted in sbiobertresolve models.

2021-12-30 09:32 UTC, closed without merging