Add new docs articles
JohnSnowLabs/spark-nlp pull request #6770
Opened 2022-01-14 11:22 UTC by agsfer

Entity Resolver Models and Features
Entity Resolver Model and NER Model Pairs
Relation Extraction Model and NER Model Pairs

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-14 12:15 UTC, muhammetsnts requested changes

2022-01-14 12:15 UTC, muhammetsnts commented on docs/en/entity_resolver_model_ner_model_pairs.md
> +title: Relation Extraction Model and NER Model Pairs
We need to change the title with `ENTITY RESOLVER MODEL AND NER MODEL PAIRS`.

2022-01-14 12:15 UTC, muhammetsnts commented on docs/en/entity_resolver_model_ner_model_pairs_edited.md
> +title: Relation Extraction Model and NER Model Pairs
- We need to change the title with `ENTITY RESOLVER MODEL AND NER MODEL PAIRS`. 
- This file and `docs/en/entity_resolver_model_ner_model_pairs.md` seem the same.

2022-01-14 12:15 UTC, muhammetsnts commented on docs/en/relation_extraction_model_pairs.md
> +title: Entity Resolver Models and Features
We need to change the title to `Relation Extraction Model and NER Model Pairs`.

2022-01-14 12:54 UTC, muhammetsnts approved these changes
Thanks!

2022-01-14 13:18 UTC, vkocaman commented
@muhammetsnts @agsfer lets out all these under one title so that we don't present all on the side bar..

title would be: `Best Practices in Using Pretrained Models in the Same Pipeline`

2022-01-15 16:48 UTC, muhammetsnts approved these changes

2022-01-15 16:57 UTC, merged