FEATURE NMH-81: Add the "Edit on GitHub" button [skip-test]
JohnSnowLabs/spark-nlp pull request #8123
Opened 2022-04-27 16:00 UTC by mahmoodbayeshi

This commit will add Edit on Github button to the models' page (NMH-81)

2022-05-05 05:46 UTC, pabla requested changes

2022-05-05 05:46 UTC, pabla commented on docs/_sass/components/_article-info.scss
> +      font-family: 'Inter';
We don't have this font on the website. Let's use the same style as we have for the text on the right.
```css
font-size: 0.85rem;
font-weight: 300;
font-family: Roboto, sans-serif;
```

2022-05-05 09:52 UTC, pabla approved these changes

2022-05-05 09:55 UTC, pabla commented
<img width="1508" alt="Screenshot 2022-05-05 at 16 54 45" src="https://user-images.githubusercontent.com/1594817/166900915-05b84cbe-924d-42d5-83f9-57e02f4ad090.png">

2022-05-09 08:23 UTC, maziyarpanahi approved these changes

2022-05-09 08:23 UTC, merged